---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
  - name: bats
  - name: bats-config
  - name: stemcell

run:
  path: bats/ci/tasks/run-bats.sh
